import type { IRecipeInput } from '~/types/types'
import { toSlug } from '@/utils'

const recipes: IRecipeInput[] = [
  {
    id: '4b7b4015-116a-4ee9-9555-586be08ccc59',
    name: 'Recipe 735',
    slug: toSlug('Recipe 735'),
    author: {
      name: 'user1',
      email: 'user1@example.com',
      image: 'favicon.ico',
    },
    category: 'Dessert',
    images: ['/images/recipe-735.jpg'],
    description: 'This is the description for Recipe 735.',
    isPublished: true,
    tags: [
      'balanced-recipe',
      'todays-recipe',
      'most-picked',
      'vegetarian',
      'low-sugar',
      'soup',
      'spicy',
      'breakfast',
      'summer',
      'healthy',
    ],
    avgRating: 3.2,
    numReviews: 133,
    ratingDistribution: [
      { rating: 1, count: 2 },
      { rating: 2, count: 31 },
      { rating: 3, count: 32 },
      { rating: 4, count: 35 },
      { rating: 5, count: 16 },
    ],
    // Transformed reviews
    reviews: [
      {
        id: '4b7b4015-116a-4ee9-9555-586be08ccc59-0',
        author: {
          name: 'Anonymous Reviewer',
          email: 'anonymous@example',
          image: 'favicon.ico',
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 0 for Recipe 735',
        date: new Date('2023-01-01T10:00:00Z'),
      },
      {
        id: '4b7b4015-116a-4ee9-9555-586be08ccc59-1',
        author: {
          name: 'Anonymous Reviewer',
          email: 'anonymous@example',
          image: 'favicon.ico',
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 1 for Recipe 735',
        date: new Date('2023-01-01T10:00:00Z'),
      },
      {
        id: '4b7b4015-116a-4ee9-9555-586be08ccc59-2',
        author: {
          name: 'Anonymous Reviewer',
          email: 'anonymous@example',
          image: 'favicon.ico',
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 2 for Recipe 735',
        date: new Date('2023-01-01T10:00:00Z'),
      },
      {
        id: '4b7b4015-116a-4ee9-9555-586be08ccc59-3',
        author: {
          name: 'Anonymous Reviewer',
          email: 'anonymous@example',
          image: 'favicon.ico',
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 3 for Recipe 735',
        date: new Date('2023-01-01T10:00:00Z'),
      },
    ],
    ingredients: ['Ingredient 1', 'Ingredient 2'],
    instructions: ['Step 1', 'Step 2', 'Step 3', 'Step 4', 'Step 5'],
    prepTimeMinutes: 10,
    cookTimeMinutes: 13,
    servings: 3,
    difficulty: 'Medium',
    cuisine: 'Indian',
    caloriesPerServing: 610,
  },
  {
    id: 'dac112dc-2e1e-4714-8094-c83cc94effe0',
    name: 'Recipe 360',
    slug: 'recipe-360',
    author: {
      name: 'user8',
      email: 'user8@example.com',
      image: '/users/user8.jpg',
    },
    category: 'Dinner',
    images: ['/images/recipe-360.jpg'],
    description: 'This is the description for Recipe 360.',
    isPublished: true,
    tags: [
      'balanced-recipe',
      'todays-recipe',
      'vegetarian',
      'soup',
      'low-fat',
      'dairy-free',
      'meal-prep',
      'comfort-food',
      'low-sugar',
    ],
    avgRating: 0.4,
    numReviews: 104,
    ratingDistribution: [
      { rating: 1, count: 21 },
      { rating: 2, count: 0 },
      { rating: 3, count: 34 },
      { rating: 4, count: 32 },
      { rating: 5, count: 6 },
    ],
    // Transformed reviews
    reviews: [
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b1b',
        author: {
          name: 'Reviewer 1',
          email: 'reviewer1@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 0 for Recipe 360',
        date: new Date('2023-01-01T10:00:00Z'),
      },
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b2',
        author: {
          name: 'Reviewer 2',
          email: 'reviewer2@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 1 for Recipe 360',
        date: new Date('2023-01-01T10:00:00Z'),
      },
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b3',
        author: {
          name: 'Reviewer 3',
          email: 'reviewer3@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 2 for Recipe 360',
        date: new Date('2023-01-01T10:00:00Z'),
      },
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b4',
        author: {
          name: 'Reviewer 4',
          email: 'reviewer4@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 3 for Recipe 360',
        date: new Date('2023-01-01T10:00:00Z'),
      },
    ],
    ingredients: ['Ingredient 1', 'Ingredient 2', 'Ingredient 3'],
    instructions: ['Step 1', 'Step 2', 'Step 3', 'Step 4', 'Step 5'],
    prepTimeMinutes: 6,
    cookTimeMinutes: 16,
    servings: 6,
    difficulty: 'Hard',
    cuisine: 'Italian',
    caloriesPerServing: 104,
  },
  {
    id: 'a9df3bec-ef77-4b43-9dcd-887c0573a90d',
    name: 'Recipe 893',
    slug: 'recipe-893',
    author: {
      name: 'user1',
      email: 'user1@example.com',
      image: '/users/user1.jpg',
    },
    category: 'Snack',
    images: ['/images/recipe-893.jpg'],
    description: 'This is the description for Recipe 893.',
    isPublished: true,
    tags: [
      'chefs-pick',
      'balanced-recipe',
      'dairy-free',
      'breakfast',
      'easy',
      'vegan',
      'low-sugar',
      'soup',
      'healthy',
    ],
    avgRating: 4.7,
    numReviews: 19,
    ratingDistribution: [
      { rating: 1, count: 14 },
      { rating: 2, count: 4 },
      { rating: 3, count: 8 },
      { rating: 4, count: 37 },
      { rating: 5, count: 40 },
    ],
    // Transformed reviews
    reviews: [
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b1b',
        author: {
          name: 'Reviewer 1',
          email: 'reviewer1@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 0 for Recipe 893',
        date: new Date('2023-01-01T10:00:00Z'),
      },
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b2b',
        author: {
          name: 'Reviewer 2',
          email: 'reviewer2@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 1 for Recipe 893',
        date: new Date('2023-01-01T10:00:00Z'),
      },
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b3b',
        author: {
          name: 'Reviewer 3',
          email: 'reviewer3@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 2 for Recipe 893',
        date: new Date('2023-01-01T10:00:00Z'),
      },
    ],
    ingredients: ['Ingredient 1', 'Ingredient 2', 'Ingredient 3'],
    instructions: ['Step 1', 'Step 2'],
    prepTimeMinutes: 27,
    cookTimeMinutes: 2,
    servings: 2,
    difficulty: 'Easy',
    cuisine: 'Mediterranean',
    caloriesPerServing: 753,
  },
  {
    id: 'e82fed86-5cff-4e46-afa4-a40e92153ac0',
    name: 'Recipe 976',
    slug: 'recipe-976',
    author: {
      name: 'user1',
      email: 'user1@example.com',
      image: 'favicon.ico',
    },
    category: 'Lunch',
    images: ['/images/recipe-976.jpg'],
    description: 'This is the description for Recipe 976.',
    isPublished: true,
    tags: [
      'balanced-recipe',
      'low-carb',
      'holiday',
      'low-sugar',
      'high-protein',
      'vegan',
      'dessert',
      'easy',
    ],
    avgRating: 2.2,
    numReviews: 89,
    ratingDistribution: [
      { rating: 1, count: 5 },
      { rating: 2, count: 47 },
      { rating: 3, count: 10 },
      { rating: 4, count: 0 },
      { rating: 5, count: 14 },
    ],
    // Transformed reviews
    reviews: [
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b4b',
        author: {
          name: 'Reviewer 1',
          email: 'reviewer1@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 0 for Recipe 976',
        date: new Date('2023-01-01T10:00:00Z'),
      },
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b5b',
        author: {
          name: 'Reviewer 2',
          email: 'reviewer2@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 1 for Recipe 976',
        date: new Date('2023-01-01T10:00:00Z'),
      },
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b6b',
        author: {
          name: 'Reviewer 3',
          email: 'reviewer3@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 2 for Recipe 976',
        date: new Date('2023-01-01T10:00:00Z'),
      },
    ],
    ingredients: [
      'Ingredient 1',
      'Ingredient 2',
      'Ingredient 3',
      'Ingredient 4',
      'Ingredient 5',
    ],
    instructions: ['Step 1', 'Step 2', 'Step 3'],
    prepTimeMinutes: 4,
    cookTimeMinutes: 14,
    servings: 4,
    difficulty: 'Medium',
    cuisine: 'American',
    caloriesPerServing: 681,
  },
  {
    id: 'd07db687-8529-420e-a507-5abd08072a4b',
    name: 'Recipe 211',
    slug: 'recipe-211',
    author: {
      name: 'user7',
      email: 'user7@example.com',
      image: 'favicon.ico',
    },
    category: 'Lunch',
    images: ['/images/recipe-211.jpg'],
    description: 'This is the description for Recipe 211.',
    isPublished: true,
    tags: [
      'chefs-pick',
      'balanced-recipe',
      'new-arrival',
      'comfort-food',
      'summer',
      'dairy-free',
      'low-carb',
      'spicy',
      'breakfast',
      'meal-prep',
    ],
    avgRating: 1.5,
    numReviews: 200,
    ratingDistribution: [
      { rating: 1, count: 25 },
      { rating: 2, count: 20 },
      { rating: 3, count: 13 },
      { rating: 4, count: 38 },
      { rating: 5, count: 19 },
    ],
    // Transformed reviews
    reviews: [
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b7b',
        author: {
          name: 'Reviewer 1',
          email: 'reviewer1@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 0 for Recipe 211',
        date: new Date('2023-01-01T10:00:00Z'),
      },
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b8b',
        author: {
          name: 'Reviewer 2',
          email: 'reviewer2@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 1 for Recipe 211',
        date: new Date('2023-01-01T10:00:00Z'),
      },
    ],
    ingredients: ['Ingredient 1', 'Ingredient 2', 'Ingredient 3'],
    instructions: ['Step 1'],
    prepTimeMinutes: 1,
    cookTimeMinutes: 9,
    servings: 3,
    difficulty: 'Hard',
    cuisine: 'Mexican',
    caloriesPerServing: 440,
  },
  {
    id: '30b944c1-29ac-469f-99c2-48579cc604c2',
    name: 'Recipe 528',
    slug: 'recipe-528',
    author: {
      name: 'user9',
      email: 'user9@example.com',
      image: 'favicon.ico',
    },
    category: 'Dinner',
    images: ['/images/recipe-528.jpg'],
    description: 'This is the description for Recipe 528.',
    isPublished: true,
    tags: [
      'balanced-recipe',
      'most-picked',
      'low-fat',
      'easy',
      'dessert',
      'dairy-free',
      'comfort-food',
      'healthy',
      'family-friendly',
    ],
    avgRating: 0.6,
    numReviews: 77,
    ratingDistribution: [
      { rating: 1, count: 18 },
      { rating: 2, count: 3 },
      { rating: 3, count: 6 },
      { rating: 4, count: 42 },
      { rating: 5, count: 26 },
    ],
    // Transformed reviews
    reviews: [
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b9b',
        author: {
          name: 'Reviewer 3',
          email: 'reviewer3@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 0 for Recipe 528',
        date: new Date('2023-01-01T10:00:00Z'),
      },
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b10b',
        author: {
          name: 'Reviewer 4',
          email: 'reviewer4@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 1 for Recipe 528',
        date: new Date('2023-01-01T10:00:00Z'),
      },
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b11b',
        author: {
          name: 'Reviewer 5',
          email: 'reviewer5@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 2 for Recipe 528',
        date: new Date('2023-01-01T10:00:00Z'),
      },
    ],
    ingredients: [
      'Ingredient 1',
      'Ingredient 2',
      'Ingredient 3',
      'Ingredient 4',
      'Ingredient 5',
    ],
    instructions: ['Step 1'],
    prepTimeMinutes: 30,
    cookTimeMinutes: 30,
    servings: 5,
    difficulty: 'Easy',
    cuisine: 'Indian',
    caloriesPerServing: 743,
  },
  {
    id: '95f6623a-f157-45bf-9234-eca48d88277e',
    name: 'Recipe 810',
    slug: 'recipe-810',
    author: {
      name: 'user5',
      email: 'user5@example.com',
      image: 'favicon.ico',
    },
    category: 'Dessert',
    images: ['/images/recipe-810.jpg'],
    description: 'This is the description for Recipe 810.',
    isPublished: true,
    tags: [
      'balanced-recipe',
      'meal-prep',
      'vegetarian',
      'holiday',
      'gluten-free',
      'low-carb',
      'dessert',
      'low-fat',
    ],
    avgRating: 0.6,
    numReviews: 83,
    ratingDistribution: [
      { rating: 1, count: 5 },
      { rating: 2, count: 38 },
      { rating: 3, count: 43 },
      { rating: 4, count: 44 },
      { rating: 5, count: 43 },
    ],
    // Transformed reviews
    reviews: [
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b12b',
        author: {
          name: 'Reviewer 6',
          email: 'reviewer6@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 0 for Recipe 810',
        date: new Date('2023-01-01T10:00:00Z'),
      },
    ],
    ingredients: ['Ingredient 1'],
    instructions: ['Step 1', 'Step 2', 'Step 3', 'Step 4', 'Step 5'],
    prepTimeMinutes: 2,
    cookTimeMinutes: 4,
    servings: 4,
    difficulty: 'Hard',
    cuisine: 'Italian',
    caloriesPerServing: 540,
  },
  {
    id: 'e4022a35-78a8-450b-8eee-699d4c5a3fd8',
    name: 'Recipe 126',
    slug: 'recipe-126',
    author: {
      name: 'user6',
      email: 'user6@example.com',
      image: 'favicon.ico',
    },
    category: 'Snack',
    images: ['/images/recipe-126.jpg'],
    description: 'This is the description for Recipe 126.',
    isPublished: true,
    tags: [
      'balanced-recipe',
      'soup',
      'low-carb',
      'kid-friendly',
      'summer',
      'holiday',
      'vegan',
      'high-protein',
    ],
    avgRating: 1.5,
    numReviews: 22,
    ratingDistribution: [
      { rating: 1, count: 6 },
      { rating: 2, count: 4 },
      { rating: 3, count: 18 },
      { rating: 4, count: 38 },
      { rating: 5, count: 50 },
    ],
    // Transformed reviews
    reviews: [
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b12b',
        author: {
          name: 'Reviewer 7',
          email: 'reviewer7@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 0 for Recipe 126',
        date: new Date('2023-01-01T10:00:00Z'),
      },
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b12b',
        author: {
          name: 'Reviewer 8',
          email: 'reviewer8@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 1 for Recipe 126',
        date: new Date('2023-01-01T10:00:00Z'),
      },
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b12b',
        author: {
          name: 'Reviewer 9',
          email: 'reviewer9@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 2 for Recipe 126',
        date: new Date('2023-01-01T10:00:00Z'),
      },
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b12b',
        author: {
          name: 'Reviewer 10',
          email: 'reviewer10@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 3 for Recipe 126',
        date: new Date('2023-01-01T10:00:00Z'),
      },
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b12b',
        author: {
          name: 'Reviewer 11',
          email: 'reviewer11@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 4 for Recipe 126',
        date: new Date('2023-01-01T10:00:00Z'),
      },
    ],
    ingredients: ['Ingredient 1'],
    instructions: ['Step 1', 'Step 2', 'Step 3', 'Step 4'],
    prepTimeMinutes: 18,
    cookTimeMinutes: 34,
    servings: 2,
    difficulty: 'Easy',
    cuisine: 'American',
    caloriesPerServing: 588,
  },
  {
    id: '294fc5c3-f8d5-4c50-b88e-5bbc33aba8da',
    name: 'Recipe 63',
    slug: 'recipe-63',
    author: {
      name: 'user4',
      email: 'user4@example.com',
      image: 'favicon.ico',
    },
    category: 'Breakfast',
    images: ['/images/recipe-63.jpg'],
    description: 'This is the description for Recipe 63.',
    isPublished: true,
    tags: [
      'most-picked',
      'new-arrival',
      'vegetarian',
      'holiday',
      'low-sugar',
      'vegan',
      'dairy-free',
      'soup',
      'easy',
    ],
    avgRating: 1.9,
    numReviews: 151,
    ratingDistribution: [
      { rating: 1, count: 28 },
      { rating: 2, count: 14 },
      { rating: 3, count: 26 },
      { rating: 4, count: 39 },
      { rating: 5, count: 40 },
    ],
    // Transformed reviews
    reviews: [
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b12b',
        author: {
          name: 'Reviewer 12',
          email: 'reviewer12@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 0 for Recipe 63',
        date: new Date('2023-01-01T10:00:00Z'),
      },
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b12b',
        author: {
          name: 'Reviewer 13',
          email: 'reviewer13@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 1 for Recipe 63',
        date: new Date('2023-01-01T10:00:00Z'),
      },
    ],
    ingredients: [
      'Ingredient 1',
      'Ingredient 2',
      'Ingredient 3',
      'Ingredient 4',
    ],
    instructions: ['Step 1'],
    prepTimeMinutes: 13,
    cookTimeMinutes: 52,
    servings: 1,
    difficulty: 'Easy',
    cuisine: 'Mexican',
    caloriesPerServing: 161,
  },
  {
    id: 'f1b84702-84be-4cb6-8d4d-773b19a645db',
    name: 'Recipe 195',
    slug: 'recipe-195',
    author: {
      name: 'user2',
      email: 'user2@example.com',
      image: '/users/user2.jpg',
    },
    category: 'Dessert',
    images: ['/images/recipe-195.jpg'],
    description: 'This is the description for Recipe 195.',
    isPublished: true,
    tags: [
      'balanced-recipe',
      'breakfast',
      'dessert',
      'family-friendly',
      'soup',
      'meal-prep',
      'high-protein',
      'vegan',
    ],
    avgRating: 2.1,
    numReviews: 82,
    ratingDistribution: [
      { rating: 1, count: 42 },
      { rating: 2, count: 0 },
      { rating: 3, count: 6 },
      { rating: 4, count: 9 },
      { rating: 5, count: 3 },
    ],
    // Transformed reviews
    reviews: [
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b12b',
        author: {
          name: 'Reviewer 14',
          email: 'reviewer14@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 0 for Recipe 195',
        date: new Date('2023-01-01T10:00:00Z'),
      },
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b12b',
        author: {
          name: 'Reviewer 15',
          email: 'reviewer15@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 1 for Recipe 195',
        date: new Date('2023-01-01T10:00:00Z'),
      },
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b12b',
        author: {
          name: 'Reviewer 16',
          email: 'reviewer16@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 2 for Recipe 195',
        date: new Date('2023-01-01T10:00:00Z'),
      },
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b12b',
        author: {
          name: 'Reviewer 17',
          email: 'reviewer17@example.com',
          image: undefined,
        },

        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 3 for Recipe 195',
        date: new Date('2023-01-01T10:00:00Z'),
      },
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b12b',
        author: {
          name: 'Reviewer 18',
          email: 'reviewer18@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 4 for Recipe 195',
        date: new Date('2023-01-01T10:00:00Z'),
      },
    ],
    ingredients: [
      'Ingredient 1',
      'Ingredient 2',
      'Ingredient 3',
      'Ingredient 4',
      'Ingredient 5',
    ],
    instructions: ['Step 1', 'Step 2', 'Step 3', 'Step 4'],
    prepTimeMinutes: 6,
    cookTimeMinutes: 13,
    servings: 5,
    difficulty: 'Hard',
    cuisine: 'Chinese',
    caloriesPerServing: 428,
  },
  {
    id: '77aca872-57e2-4d52-a336-46407ecd5ca3',
    name: 'Recipe 92',
    slug: 'recipe-92',
    author: {
      name: 'user10',
      email: 'user10@example.com',
      image: 'favicon.ico',
    },
    category: 'Snack',
    images: ['/images/recipe-92.jpg'],
    description: 'This is the description for Recipe 92.',
    isPublished: true,
    tags: [
      'vegan',
      'kid-friendly',
      'high-protein',
      'spicy',
      'healthy',
      'meal-prep',
      'dairy-free',
    ],
    avgRating: 3.4,
    numReviews: 67,
    ratingDistribution: [
      { rating: 1, count: 35 },
      { rating: 2, count: 46 },
      { rating: 3, count: 43 },
      { rating: 4, count: 34 },
      { rating: 5, count: 4 },
    ],
    // Transformed reviews
    reviews: [
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b12b',
        author: {
          name: 'Reviewer 19',
          email: 'reviewer19@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 0 for Recipe 92',
        date: new Date('2023-01-01T10:00:00Z'),
      },
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b12b',
        author: {
          name: 'Reviewer 20',
          email: 'reviewer20@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 1 for Recipe 92',
        date: new Date('2023-01-01T10:00:00Z'),
      },
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b12b',
        author: {
          name: 'Reviewer 21',
          email: 'reviewer21@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 2 for Recipe 92',
        date: new Date('2023-01-01T10:00:00Z'),
      },
    ],
    ingredients: ['Ingredient 1'],
    instructions: ['Step 1', 'Step 2'],
    prepTimeMinutes: 23,
    cookTimeMinutes: 56,
    servings: 5,
    difficulty: 'Hard',
    cuisine: 'Indian',
    caloriesPerServing: 728,
  },
  {
    id: '5a7f8ef9-9b4d-4727-84c4-930a1be1040c',
    name: 'Recipe 391',
    slug: 'recipe-391',
    author: {
      name: 'user2',
      email: 'user2@example.com',
      image: 'favicon.ico',
    },
    category: 'Lunch',
    images: ['/images/recipe-391.jpg'],
    description: 'This is the description for Recipe 391.',
    isPublished: true,
    tags: [
      'most-picked',
      'summer',
      'kid-friendly',
      'quick',
      'vegetarian',
      'dessert',
      'comfort-food',
      'family-friendly',
    ],
    avgRating: 3.2,
    numReviews: 25,
    ratingDistribution: [
      { rating: 1, count: 21 },
      { rating: 2, count: 33 },
      { rating: 3, count: 21 },
      { rating: 4, count: 41 },
      { rating: 5, count: 19 },
    ],
    // Transformed reviews
    reviews: [
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b12b',
        author: {
          name: 'Reviewer 22',
          email: 'reviewer22@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 0 for Recipe 391',
        date: new Date('2023-01-01T10:00:00Z'),
      },
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b12b',
        author: {
          name: 'Reviewer 23',
          email: 'reviewer23@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 1 for Recipe 391',
        date: new Date('2023-01-01T10:00:00Z'),
      },
    ],
    ingredients: ['Ingredient 1'],
    instructions: ['Step 1', 'Step 2', 'Step 3', 'Step 4'],
    prepTimeMinutes: 21,
    cookTimeMinutes: 9,
    servings: 3,
    difficulty: 'Easy',
    cuisine: 'Indian',
    caloriesPerServing: 245,
  },
  {
    id: 'b974a46d-4f54-4a82-8abc-d37525e4a172',
    name: 'Recipe 180',
    slug: 'recipe-180',
    author: {
      name: 'user3',
      email: 'user3@example.com',
      image: 'favicon.ico',
    },
    category: 'Dinner',
    images: ['/images/recipe-180.jpg'],
    description: 'This is the description for Recipe 180.',
    isPublished: true,
    tags: [
      'quick',
      'balanced-recipe',
      'vegan',
      'high-protein',
      'comfort-food',
      'soup',
      'meal-prep',
      'summer',
      'vegetarian',
    ],
    avgRating: 2.3,
    numReviews: 180,
    ratingDistribution: [
      { rating: 1, count: 26 },
      { rating: 2, count: 36 },
      { rating: 3, count: 19 },
      { rating: 4, count: 34 },
      { rating: 5, count: 27 },
    ],
    // Transformed reviews
    reviews: [
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b12b',
        author: {
          name: 'Reviewer 24',
          email: 'reviewer24@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 0 for Recipe 180',
        date: new Date('2023-01-01T10:00:00Z'),
      },
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b12b',
        author: {
          name: 'Reviewer 25',
          email: 'reviewer25@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 1 for Recipe 180',
        date: new Date('2023-01-01T10:00:00Z'),
      },
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b12b',
        author: {
          name: 'Reviewer 26',
          email: 'reviewer26@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 2 for Recipe 180',
        date: new Date('2023-01-01T10:00:00Z'),
      },
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b12b',
        author: {
          name: 'Reviewer 27',
          email: 'reviewer27@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 3 for Recipe 180',
        date: new Date('2023-01-01T10:00:00Z'),
      },
    ],
    ingredients: ['Ingredient 1', 'Ingredient 2'],
    instructions: ['Step 1'],
    prepTimeMinutes: 23,
    cookTimeMinutes: 1,
    servings: 3,
    difficulty: 'Easy',
    cuisine: 'American',
    caloriesPerServing: 239,
  },
  {
    id: '4e748239-6ca0-44a6-b93b-62c15ec84320',
    name: 'Recipe 279',
    slug: 'recipe-279',
    author: {
      name: 'user3',
      email: 'user3@example.com',
      image: 'favicon.ico',
    },
    category: 'Breakfast',
    images: ['/images/recipe-279.jpg'],
    description: 'This is the description for Recipe 279.',
    isPublished: true,
    tags: [
      'kid-friendly',
      'low-fat',
      'summer',
      'easy',
      'gluten-free',
      'family-friendly',
      'healthy',
    ],
    avgRating: 5.0,
    numReviews: 38,
    ratingDistribution: [
      { rating: 1, count: 38 },
      { rating: 2, count: 36 },
      { rating: 3, count: 8 },
      { rating: 4, count: 7 },
      { rating: 5, count: 48 },
    ],
    // Transformed reviews
    reviews: [
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b12b',
        author: {
          name: 'Reviewer 28',
          email: 'reviewer28@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 0 for Recipe 279',
        date: new Date('2023-01-01T10:00:00Z'),
      },
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b12b',
        author: {
          name: 'Reviewer 29',
          email: 'reviewer29@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 1 for Recipe 279',
        date: new Date('2023-01-01T10:00:00Z'),
      },
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b12b',
        author: {
          name: 'Reviewer 30',
          email: 'reviewer30@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 2 for Recipe 279',
        date: new Date('2023-01-01T10:00:00Z'),
      },
    ],
    ingredients: ['Ingredient 1'],
    instructions: ['Step 1', 'Step 2', 'Step 3', 'Step 4'],
    prepTimeMinutes: 7,
    cookTimeMinutes: 25,
    servings: 2,
    difficulty: 'Medium',
    cuisine: 'Chinese',
    caloriesPerServing: 761,
  },
  {
    id: '8fae3a12-2e2e-4860-ac79-cca1bd1070bd',
    name: 'Recipe 694',
    slug: 'recipe-694',
    author: {
      name: 'user10',
      email: 'user10@example.com',
      image: 'favicon.ico',
    },
    category: 'Snack',
    images: ['/images/recipe-694.jpg'],
    description: 'This is the description for Recipe 694.',
    isPublished: true,
    tags: [
      'gluten-free',
      'vegetarian',
      'meal-prep',
      'soup',
      'dairy-free',
      'easy',
      'breakfast',
    ],
    avgRating: 4.2,
    numReviews: 169,
    ratingDistribution: [
      { rating: 1, count: 34 },
      { rating: 2, count: 19 },
      { rating: 3, count: 30 },
      { rating: 4, count: 43 },
      { rating: 5, count: 12 },
    ],
    // Transformed reviews
    reviews: [
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b12b',
        author: {
          name: 'Reviewer 28',
          email: 'reviewer28@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 0 for Recipe 694',
        date: new Date('2023-01-01T10:00:00Z'),
      },
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b12b',
        author: {
          name: 'Reviewer 29',
          email: 'reviewer29@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 1 for Recipe 694',
        date: new Date('2023-01-01T10:00:00Z'),
      },
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b12b',
        author: {
          name: 'Reviewer 30',
          email: 'reviewer30@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 2 for Recipe 694',
        date: new Date('2023-01-01T10:00:00Z'),
      },
    ],
    ingredients: ['Ingredient 1'],
    instructions: ['Step 1'],
    prepTimeMinutes: 28,
    cookTimeMinutes: 10,
    servings: 5,
    difficulty: 'Hard',
    cuisine: 'American',
    caloriesPerServing: 604,
  },
  {
    id: 'ef5ceb7a-76bb-4f06-8dde-f7f94e5176e6',
    name: 'Recipe 467',
    slug: 'recipe-467',
    author: {
      name: 'user5',
      email: 'user5@example.com',
      image: 'favicon.ico',
    },
    category: 'Dinner',
    images: ['/images/recipe-467.jpg'],
    description: 'This is the description for Recipe 467.',
    isPublished: true,
    tags: [
      'new-arrival',
      'family-friendly',
      'meal-prep',
      'soup',
      'vegetarian',
      'breakfast',
      'gluten-free',
      'spicy',
    ],
    avgRating: 3.4,
    numReviews: 152,
    ratingDistribution: [
      { rating: 1, count: 19 },
      { rating: 2, count: 39 },
      { rating: 3, count: 48 },
      { rating: 4, count: 30 },
      { rating: 5, count: 1 },
    ],
    // Transformed reviews
    reviews: [
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b12b',
        author: {
          name: 'Reviewer 31',
          email: 'reviewer31@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 0 for Recipe 467',
        date: new Date('2023-01-01T10:00:00Z'),
      },
    ],
    ingredients: ['Ingredient 1', 'Ingredient 2', 'Ingredient 3'],
    instructions: ['Step 1', 'Step 2', 'Step 3', 'Step 4', 'Step 5'],
    prepTimeMinutes: 6,
    cookTimeMinutes: 49,
    servings: 3,
    difficulty: 'Medium',
    cuisine: 'Italian',
    caloriesPerServing: 225,
  },
  {
    id: '49668359-23f7-4178-b961-5abda9a61310',
    name: 'Recipe 940',
    slug: 'recipe-940',
    author: {
      name: 'user7',
      email: 'user7@example.com',
      image: 'favicon.ico',
    },
    category: 'Dessert',
    images: ['/images/recipe-940.jpg'],
    description: 'This is the description for Recipe 940.',
    isPublished: true,
    tags: [
      'featured',
      'easy',
      'holiday',
      'dessert',
      'breakfast',
      'vegetarian',
      'summer',
      'family-friendly',
    ],
    avgRating: 0.6,
    numReviews: 123,
    ratingDistribution: [
      { rating: 1, count: 20 },
      { rating: 2, count: 16 },
      { rating: 3, count: 38 },
      { rating: 4, count: 19 },
      { rating: 5, count: 15 },
    ],
    // Transformed reviews
    reviews: [
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b12b',
        author: {
          name: 'Reviewer 32',
          email: 'reviewer32@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 0 for Recipe 940',
        date: new Date('2023-01-01T10:00:00Z'),
      },
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b12b',
        author: {
          name: 'Reviewer 33',
          email: 'reviewer33@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 1 for Recipe 940',
        date: new Date('2023-01-01T10:00:00Z'),
      },
    ],
    ingredients: [
      'Ingredient 1',
      'Ingredient 2',
      'Ingredient 3',
      'Ingredient 4',
    ],
    instructions: ['Step 1', 'Step 2', 'Step 3', 'Step 4'],
    prepTimeMinutes: 13,
    cookTimeMinutes: 29,
    servings: 6,
    difficulty: 'Easy',
    cuisine: 'Indian',
    caloriesPerServing: 189,
  },
  {
    id: 'ad07d9d1-ea8b-4602-a036-e6d4e0370e27',
    name: 'Recipe 259',
    slug: 'recipe-259',
    author: {
      name: 'user2',
      email: 'user2@example.com',
      image: '/users/user2.jpg',
    },
    category: 'Breakfast',
    images: ['/images/recipe-259.jpg'],
    description: 'This is the description for Recipe 259.',
    isPublished: true,
    tags: [
      'balanced-recipe',
      'breakfast',
      'holiday',
      'dessert',
      'comfort-food',
      'soup',
      'high-protein',
      'family-friendly',
    ],
    avgRating: 1.2,
    numReviews: 87,
    ratingDistribution: [
      { rating: 1, count: 23 },
      { rating: 2, count: 44 },
      { rating: 3, count: 23 },
      { rating: 4, count: 13 },
      { rating: 5, count: 29 },
    ],
    // Transformed reviews
    reviews: [
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b12b',
        author: {
          name: 'Reviewer 32',
          email: 'reviewer32@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 0 for Recipe 259',
        date: new Date('2023-01-01T10:00:00Z'),
      },
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b12b',
        author: {
          name: 'Reviewer 33',
          email: 'reviewer33@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 1 for Recipe 259',
        date: new Date('2023-01-01T10:00:00Z'),
      },
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b12b',
        author: {
          name: 'Reviewer 34',
          email: 'reviewer34@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 2 for Recipe 259',
        date: new Date('2023-01-01T10:00:00Z'),
      },
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b12b',
        author: {
          name: 'Reviewer 35',
          email: 'reviewer35@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 3 for Recipe 259',
        date: new Date('2023-01-01T10:00:00Z'),
      },
    ],
    ingredients: ['Ingredient 1', 'Ingredient 2', 'Ingredient 3'],
    instructions: ['Step 1', 'Step 2'],
    prepTimeMinutes: 7,
    cookTimeMinutes: 43,
    servings: 2,
    difficulty: 'Easy',
    cuisine: 'Italian',
    caloriesPerServing: 750,
  },
  {
    id: 'a8574500-98ea-4beb-8433-df6ac94b2589',
    name: 'Recipe 834',
    slug: 'recipe-834',
    author: {
      name: 'user2',
      email: 'user2@example.com',
      image: 'favicon.ico',
    },
    category: 'Dinner',
    images: ['/images/recipe-834.jpg'],
    description: 'This is the description for Recipe 834.',
    isPublished: true,
    tags: [
      'featured',
      'dairy-free',
      'gluten-free',
      'breakfast',
      'vegetarian',
      'healthy',
      'kid-friendly',
      'soup',
    ],
    avgRating: 2.4,
    numReviews: 35,
    ratingDistribution: [
      { rating: 1, count: 19 },
      { rating: 2, count: 6 },
      { rating: 3, count: 16 },
      { rating: 4, count: 21 },
      { rating: 5, count: 25 },
    ],
    // Transformed reviews
    reviews: [
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b12b',
        author: {
          name: 'Reviewer 36',
          email: 'reviewer36@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 0 for Recipe 834',
        date: new Date('2023-01-01T10:00:00Z'),
      },
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b12b',
        author: {
          name: 'Reviewer 37',
          email: 'reviewer37@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 1 for Recipe 834',
        date: new Date('2023-01-01T10:00:00Z'),
      },
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b12b',
        author: {
          name: 'Reviewer 38',
          email: 'reviewer38@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 2 for Recipe 834',
        date: new Date('2023-01-01T10:00:00Z'),
      },
    ],
    ingredients: ['Ingredient 1'],
    instructions: ['Step 1', 'Step 2'],
    prepTimeMinutes: 22,
    cookTimeMinutes: 1,
    servings: 5,
    difficulty: 'Medium',
    cuisine: 'Mexican',
    caloriesPerServing: 734,
  },
  {
    id: '447f1e5e-3105-4dd2-a58a-2d30992a431b',
    name: 'Recipe 842',
    slug: 'recipe-842',
    author: {
      name: 'user2',
      email: 'user2@example.com',
      image: '/users/user2.jpg',
    },
    category: 'Dessert',
    images: ['/images/recipe-842.jpg'],
    description: 'This is the description for Recipe 842.',
    isPublished: true,
    tags: [
      'featured',
      'low-sugar',
      'easy',
      'comfort-food',
      'spicy',
      'healthy',
      'kid-friendly',
      'soup',
    ],
    avgRating: 1.2,
    numReviews: 200,
    ratingDistribution: [
      { rating: 1, count: 26 },
      { rating: 2, count: 50 },
      { rating: 3, count: 40 },
      { rating: 4, count: 43 },
      { rating: 5, count: 40 },
    ],
    // Transformed reviews
    reviews: [
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b12b',
        author: {
          name: 'Reviewer 39',
          email: 'reviewer39@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 0 for Recipe 842',
        date: new Date('2023-01-01T10:00:00Z'),
      },
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b12b',
        author: {
          name: 'Reviewer 40',
          email: 'reviewer40@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 1 for Recipe 842',
        date: new Date('2023-01-01T10:00:00Z'),
      },
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b12b',
        author: {
          name: 'Reviewer 41',
          email: 'reviewer41@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 2 for Recipe 842',
        date: new Date('2023-01-01T10:00:00Z'),
      },
    ],
    ingredients: ['Ingredient 1', 'Ingredient 2', 'Ingredient 3'],
    instructions: ['Step 1', 'Step 2', 'Step 3', 'Step 4', 'Step 5'],
    prepTimeMinutes: 12,
    cookTimeMinutes: 59,
    servings: 5,
    difficulty: 'Easy',
    cuisine: 'American',
    caloriesPerServing: 612,
  },
  {
    id: '0dd54879-1607-4d1e-81e5-7799436ab0a9',
    name: 'Recipe 277',
    slug: 'recipe-277',
    author: {
      name: 'user8',
      email: 'user8@example.com',
      image: '/users/user8.jpg',
    },
    category: 'Dessert',
    images: ['/images/recipe-277.jpg'],
    description: 'This is the description for Recipe 277.',
    isPublished: true,
    tags: [
      'new-arrival',
      'healthy',
      'easy',
      'low-sugar',
      'soup',
      'dairy-free',
      'quick',
      'low-carb',
    ],
    avgRating: 3.4,
    numReviews: 172,
    ratingDistribution: [
      { rating: 1, count: 3 },
      { rating: 2, count: 0 },
      { rating: 3, count: 19 },
      { rating: 4, count: 15 },
      { rating: 5, count: 45 },
    ],
    // Transformed reviews
    reviews: [
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b12b',
        author: {
          name: 'Reviewer 42',
          email: 'reviewer42@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 0 for Recipe 277',
        date: new Date('2023-01-01T10:00:00Z'),
      },
    ],
    ingredients: ['Ingredient 1'],
    instructions: ['Step 1'],
    prepTimeMinutes: 18,
    cookTimeMinutes: 24,
    servings: 2,
    difficulty: 'Medium',
    cuisine: 'Mexican',
    caloriesPerServing: 134,
  },
  {
    id: 'dcaee5f6-12aa-4a9a-9085-8cec1d8baf21',
    name: 'Recipe 215',
    slug: 'recipe-215',
    author: {
      name: 'user7',
      email: 'user7@example.com',
      image: 'favicon.ico',
    },
    category: 'Dinner',
    images: ['/images/recipe-215.jpg'],
    description: 'This is the description for Recipe 215.',
    isPublished: true,
    tags: [
      'low-fat',
      'vegan',
      'quick',
      'meal-prep',
      'spicy',
      'low-carb',
      'dessert',
    ],
    avgRating: 4.9,
    numReviews: 6,
    ratingDistribution: [
      { rating: 1, count: 21 },
      { rating: 2, count: 16 },
      { rating: 3, count: 41 },
      { rating: 4, count: 37 },
      { rating: 5, count: 38 },
    ],
    // Transformed reviews
    reviews: [
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b12b',
        author: {
          name: 'Reviewer 43',
          email: 'reviewer43@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 0 for Recipe 215',
        date: new Date('2023-01-01T10:00:00Z'),
      },
    ],
    ingredients: ['Ingredient 1', 'Ingredient 2'],
    instructions: ['Step 1', 'Step 2', 'Step 3', 'Step 4'],
    prepTimeMinutes: 24,
    cookTimeMinutes: 47,
    servings: 1,
    difficulty: 'Easy',
    cuisine: 'Chinese',
    caloriesPerServing: 270,
  },
  {
    id: '10548333-c790-458f-b268-40e92c3071b1',
    name: 'Recipe 731',
    slug: 'recipe-731',
    author: {
      name: 'user6',
      email: 'user6@example.com',
      image: '/users/user6.jpg',
    },
    category: 'Breakfast',
    images: ['/images/recipe-731.jpg'],
    description: 'This is the description for Recipe 731.',
    isPublished: true,
    tags: [
      'todays-recipe',
      'featured',
      'new-arrival',
      'healthy',
      'low-carb',
      'comfort-food',
      'dairy-free',
      'spicy',
      'breakfast',
      'quick',
    ],
    avgRating: 0.6,
    numReviews: 187,
    ratingDistribution: [
      { rating: 1, count: 39 },
      { rating: 2, count: 33 },
      { rating: 3, count: 39 },
      { rating: 4, count: 2 },
      { rating: 5, count: 10 },
    ],
    // Transformed reviews
    reviews: [
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b12b',
        author: {
          name: 'Reviewer 44',
          email: 'reviewer44@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 0 for Recipe 731',
        date: new Date('2023-01-01T10:00:00Z'),
      },
    ],
    ingredients: [
      'Ingredient 1',
      'Ingredient 2',
      'Ingredient 3',
      'Ingredient 4',
    ],
    instructions: ['Step 1', 'Step 2', 'Step 3', 'Step 4'],
    prepTimeMinutes: 16,
    cookTimeMinutes: 41,
    servings: 3,
    difficulty: 'Hard',
    cuisine: 'Mediterranean',
    caloriesPerServing: 689,
  },
  {
    id: 'ce5282d0-0346-4413-a8f3-2a5748bb3f99',
    name: 'Recipe 113',
    slug: 'recipe-113',
    author: {
      name: 'user3',
      email: 'user3@example.com',
      image: '/users/user3.jpg',
    },
    category: 'Lunch',
    images: ['/images/recipe-113.jpg'],
    description: 'This is the description for Recipe 113.',
    isPublished: true,
    tags: [
      'comfort-food',
      'high-protein',
      'low-fat',
      'dairy-free',
      'dessert',
      'gluten-free',
      'vegetarian',
    ],
    avgRating: 4.6,
    numReviews: 133,
    ratingDistribution: [
      { rating: 1, count: 41 },
      { rating: 2, count: 5 },
      { rating: 3, count: 8 },
      { rating: 4, count: 26 },
      { rating: 5, count: 44 },
    ],
    // Transformed reviews
    reviews: [
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b13b',
        author: {
          name: 'Reviewer 45',
          email: 'reviewer45@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 0 for Recipe 113',
        date: new Date('2023-01-01T10:00:00Z'),
      },
      {
        id: '9d0d7f6b-5b4b-4b2b-9b7b-6b5b4b3b2b13b',
        author: {
          name: 'Reviewer 46',
          email: 'reviewer46@example.com',
          image: undefined,
        },
        reviewerName: 'Anonymous Reviewer',
        rating: 5,
        comment: 'Review 1 for Recipe 113',
        date: new Date('2023-01-01T10:00:00Z'),
      },
    ],
    ingredients: ['Ingredient 1', 'Ingredient 2'],
    instructions: ['Step 1', 'Step 2', 'Step 3'],
    prepTimeMinutes: 28,
    cookTimeMinutes: 9,
    servings: 3,
    difficulty: 'Easy',
    cuisine: 'Mexican',
    caloriesPerServing: 257,
  },
]

const data = {
  recipes,
  headerMenus: [
    {
      name: "Today's Recipes",
      href: '/search?tag=todays-recipe',
    },
    {
      name: 'New Recipes',
      href: '/search?tag=new-arrival',
    },
    {
      name: 'Chef’s Picks',
      href: '/search?tag=chefs-pick',
    },
    {
      name: 'Most Popular',
      href: '/search?tag=most-popular',
    },
    {
      name: 'Recently Viewed',
      href: '/#recently-viewed',
    },
    {
      name: 'Help & Support',
      href: '/help-support',
    },
  ],
  carousels: [
    {
      title: 'Most Popular Vegan Recipes',
      buttonCaption: 'Cook Now',
      image: '/images/vegan-banner.jpg',
      url: '/search?tags=vegan',
      isPublished: true,
    },
    {
      title: 'Top Rated Comfort Foods',
      buttonCaption: 'Explore Recipes',
      image: '/images/comfort-banner.jpg',
      url: '/search?tags=comfort-food',
      isPublished: true,
    },
    {
      title: 'Quick & Easy Weeknight Dinners',
      buttonCaption: 'View Dishes',
      image: '/images/easy-banner.jpg',
      url: '/search?tags=easy',
      isPublished: true,
    },
  ],
}

export default data
